export enum PlanTypes {
    UNA_X_SEMANA = 'UNA_X_SEMANA',
    DOS_X_SEMANA = 'DOS_X_SEMANA',
    TRES_X_SEMANA = 'TRES_X_SEMANA',
    CUATRO_X_SEMANA = 'CUATRO_X_SEMANA',
    SEMANA_COMPLETA = 'SEMANA_COMPLETA'
}
